# Generated by Django 3.0.4 on 2022-04-18 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Insertintodb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Roll_NUmber', models.CharField(max_length=30)),
                ('Name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=30)),
                ('time', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'student_records',
            },
        ),
    ]
