# Generated by Django 3.2.12 on 2022-03-18 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Homepage',
            fields=[
                ('Roll_NUmber', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=30)),
                ('Image_Vector', models.TextField()),
            ],
            options={
                'db_table': 'students',
            },
        ),
    ]
