# Generated by Django 3.0.4 on 2022-03-27 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='email',
            field=models.CharField(default=True, max_length=100),
            preserve_default=False,
        ),
    ]
